### ISSUE TITLE
Implement vertx-apex

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#1]
Building blocks for creating HTTP and REST applications

**Comment by purplefox** [comment]
@pmlopes Hey Paulo, are you in a position to take any of the remaining apex tasks (porting from Yoke?)

**Comment by pmlopes** [comment]
Hi it is a very hectic time for me now and before the start of next year i dont think i can make any real PR...

**Comment by purplefox** [comment]
No problem, I fully understand.

Most of the work is done now, there are a few bits and pieces left. If you don't have the chance to implement anything that's fine, however I would like you to review what's been done, if possible. I am sure there are things that can be improved and that you have many suggestions to make.
