### ISSUE TITLE
Email service

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#10]
Asynchronous IMAP and SMTP support

**Comment by purplefox** [comment]
@alexlehm Can you accept my invitation to vert.x then I can assign this to you.. :)

**Comment by alexlehm** [comment]
i have accepted the invitation yesterday evening, it should work now.

**Comment by purplefox** [comment]
Ah. It seems I needed to add you as collaborators first :)

**Comment by purplefox** [comment]
Alex - could you take a look at the development process here https://github.com/vert-x3/issues-and-wiki/wiki/Vert.x-3-Development-Process - this needs to be followed by all devs working on official modules.
If all looks ok to you, could you put your initial work in an "initial-work" branch (as described in the process) and contiunue to work from there?
Thanks.

**Comment by purplefox** [comment]
I've created a new repository here where you can create the branch. https://github.com/vert-x3/vertx-mail

**Comment by alexlehm** [comment]
I think I need write access to the repository, currently I get access denied when I try to push to the repo.

**Comment by purplefox** [comment]
I've just granted you access :)
