### ISSUE TITLE
Event bus socket interop

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#14]
Simple JSON text protocol so clients can open a socket and talk to the Vert.x event bus. 

Very similar to what we already have in the Vert.x event bus bridge. 

It's really a matter of fine tuning and publishing the protocol, and developing from what we already have in the event bus bridge.

**Comment by wprice** [comment]
I actually think I can do this with the Redis stuff. Might be a good place to start with the wire protocol. Proving ground as it were.

**Comment by purplefox** [comment]
Weston- redis already has its own wire protocol, and the (almost ported) redis service implements that already.

**Comment by wprice** [comment]
yes, I know it has it's own protocol, that's not what I mean. I simply meant if we are starting to talk to the EB via JSON, ultimately that will expand to the EB wire protocol stuff in one way or another. 

I meant that I could do this task in conjunction with the Redis work.
