### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#22]
Create various end to end examples / tutorials showing how to create typical applications with Vert.x

**Comment by wprice** [comment]
Cool name.

**Comment by purplefox** [comment]
Thanks, but I didn't invent it :)

**Comment by wprice** [comment]
I'm just glad we didn't call it Pet Store :-)

Lest we all forget how good that was...

**Comment by purplefox** [comment]
Please stop reminding me of JavaEE! ;)
