### ISSUE TITLE
Handling issues page contains dead links to Waffle.io

### ISSUE THREAD

**Issue by jlengrand** [vert-x3/issues-and-wiki#36]
### Version

Latest wiki, the [Handling issues](https://github.com/vert-x3/wiki/wiki/Handling-Issues) page specifically, contains links to Waffle for handling issues.
[Waffle has closed down last year](https://news.ycombinator.com/item?id=19400833), and those links are now dead. 

### Context

I was just reading the doc, looking into how to contribute to vert-x :).
Because this is a wiki I can't easily make a pull request :).

### Do you have a reproducer?

Click the waffle links at the bottom of the page. [This one](https://waffle.io/vert-x3/vertx-stack) and [this one](https://waffle.io/eclipse/vert.x). They are both 404.

### Extra

[There seems to be a few alternatives](https://dev.to/tammalee/waffleio-alternatives-4adb), but none that seems quite as loved just yet.

**Comment by tsegismont** [comment]
@jlengrand thanks for the heads-up, I removed the section related to Waffle.

**Comment by jlengrand** [comment]
Cheers!
