### ISSUE TITLE
RoutingContextImpl requires a request of type HttpServerRequestInternal and not HttpServerRequest as defined on the constructor

### ISSUE THREAD

**Issue by njacinto** [vert-x3/issues-and-wiki#39]
On version 4.0.3, the constructor of the class RoutingContextImpl requires an HttpServerRequest object but this one will be cast later to HttpServerRequestInternal throwing a ClassCastException.

**Comment by tsegismont** [comment]
Can you open this in the vertx-web repo please? Thank you

**Comment by njacinto** [comment]
> Can you open this in the vertx-web repo please? Thank you

Sorry. I didn;t notice that I was on the wrong project. Thank you
