### ISSUE TITLE
Complete metrics

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#8]
- Better selection of metrics
- Metrics output to event bus
- Expose metrics registry so users can expose their own metrics

**Comment by purplefox** [comment]
@heri333 Can you accept my invitation to vert.x then I can assign this to you.. :)

**Comment by heri333** [comment]
I had accepted it already :)

**Comment by purplefox** [comment]
Ah. It seems I needed to add you as collaborators first :)

**Comment by purplefox** [comment]
@heri333 Heribert - could you take a look at the development process here https://github.com/vert-x3/issues-and-wiki/wiki/Vert.x-3-Development-Process - this needs to be followed by all devs working on official modules.
If all looks ok to you, could you create a branch in the vertx-metrics repo (as described in the process) and contiunue to work from there?
Thanks.

**Comment by heri333** [comment]
Yes, I will do it that way in a few days.
