### ISSUE TITLE
Redis service

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues-and-wiki#9]
Port from Vert.x 2.x

**Comment by wprice** [comment]
From 

[https://github.com/vert-x/mod-redis.git](https://github.com/vert-x/mod-redis.git)

Obvious items in the port

1) Mavenize
2) Package names
3) Formatting
4) Convert for 2.x module sytem to V3
5) Enhancements
    I could see custom data handlers on both 'client' and 'server' in terms of pluggable ways to treat varying types of data based on predicates etc
